### ISSUE TITLE
Can you provide me test case for Discount Coupon Offer?

### ISSUE THREAD

**Issue by shriyapaudyal** [shriyapaudyal/TestCasesRepository#4]

**Comment by Bhaveshgoldsmith** [comment]
I have general test cases for Discount coupon offer, you can refer the same.I have generated a pull request for the same.
[https://github.com/shriyapaudyal/TestCasesRepository/pull/3#issue-1524376856](url)

**Comment by shriyapaudyal** [comment]
Thank You so much.
